// Generated by gencpp from file rand_walker/BumperEvent.msg
// DO NOT EDIT!


#ifndef RAND_WALKER_MESSAGE_BUMPEREVENT_H
#define RAND_WALKER_MESSAGE_BUMPEREVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rand_walker
{
template <class ContainerAllocator>
struct BumperEvent_
{
  typedef BumperEvent_<ContainerAllocator> Type;

  BumperEvent_()
    : bumper(0)
    , state(0)  {
    }
  BumperEvent_(const ContainerAllocator& _alloc)
    : bumper(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _bumper_type;
  _bumper_type bumper;

   typedef uint8_t _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LEFT)
  #undef LEFT
#endif
#if defined(_WIN32) && defined(CENTER)
  #undef CENTER
#endif
#if defined(_WIN32) && defined(RIGHT)
  #undef RIGHT
#endif
#if defined(_WIN32) && defined(RELEASED)
  #undef RELEASED
#endif
#if defined(_WIN32) && defined(PRESSED)
  #undef PRESSED
#endif

  enum {
    LEFT = 0u,
    CENTER = 1u,
    RIGHT = 2u,
    RELEASED = 0u,
    PRESSED = 1u,
  };


  typedef boost::shared_ptr< ::rand_walker::BumperEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rand_walker::BumperEvent_<ContainerAllocator> const> ConstPtr;

}; // struct BumperEvent_

typedef ::rand_walker::BumperEvent_<std::allocator<void> > BumperEvent;

typedef boost::shared_ptr< ::rand_walker::BumperEvent > BumperEventPtr;
typedef boost::shared_ptr< ::rand_walker::BumperEvent const> BumperEventConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rand_walker::BumperEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rand_walker::BumperEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rand_walker::BumperEvent_<ContainerAllocator1> & lhs, const ::rand_walker::BumperEvent_<ContainerAllocator2> & rhs)
{
  return lhs.bumper == rhs.bumper &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rand_walker::BumperEvent_<ContainerAllocator1> & lhs, const ::rand_walker::BumperEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rand_walker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rand_walker::BumperEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rand_walker::BumperEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rand_walker::BumperEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rand_walker::BumperEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rand_walker::BumperEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rand_walker::BumperEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rand_walker::BumperEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffe360cd50f14f9251d9844083e72ac5";
  }

  static const char* value(const ::rand_walker::BumperEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffe360cd50f14f92ULL;
  static const uint64_t static_value2 = 0x51d9844083e72ac5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rand_walker::BumperEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rand_walker/BumperEvent";
  }

  static const char* value(const ::rand_walker::BumperEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rand_walker::BumperEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# bumper\n"
"uint8 LEFT   = 0\n"
"uint8 CENTER = 1\n"
"uint8 RIGHT  = 2\n"
"\n"
"# state\n"
"uint8 RELEASED = 0\n"
"uint8 PRESSED  = 1\n"
"\n"
"uint8 bumper\n"
"uint8 state\n"
;
  }

  static const char* value(const ::rand_walker::BumperEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rand_walker::BumperEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bumper);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BumperEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rand_walker::BumperEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rand_walker::BumperEvent_<ContainerAllocator>& v)
  {
    s << indent << "bumper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bumper);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAND_WALKER_MESSAGE_BUMPEREVENT_H
